# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(642, 545)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(370, 80, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.three = QtWidgets.QLineEdit(Form)
        self.three.setGeometry(QtCore.QRect(150, 190, 111, 45))
        self.three.setMinimumSize(QtCore.QSize(0, 45))
        self.three.setMaximumSize(QtCore.QSize(16777215, 45))
        self.three.setStyleSheet("QLineEdit {\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;\n"
"    background-color: transparent;\n"
"}\n"
"QLineEdit: hover{\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"QLineEdit: focus \n"
"{\n"
"     border-bottom: 1px solid rgb(18,183,245);\n"
"}")
        self.three.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.three.setObjectName("three")
        self.submit = QtWidgets.QPushButton(Form)
        self.submit.setEnabled(True)
        self.submit.setGeometry(QtCore.QRect(30, 330, 321, 45))
        self.submit.setMinimumSize(QtCore.QSize(0, 45))
        self.submit.setMaximumSize(QtCore.QSize(16777215, 45))
        self.submit.setStyleSheet("QPushButton {\n"
"    background-color: rgb(33,174,250);\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(72,203,250);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85,85,255);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(148, 146, 149);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/login/images/safe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submit.setIcon(icon)
        self.submit.setObjectName("submit")
        self.returnbutton = QtWidgets.QPushButton(Form)
        self.returnbutton.setEnabled(True)
        self.returnbutton.setGeometry(QtCore.QRect(530, 10, 91, 45))
        self.returnbutton.setMinimumSize(QtCore.QSize(0, 45))
        self.returnbutton.setMaximumSize(QtCore.QSize(16777215, 45))
        self.returnbutton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(33,174,250);\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(72,203,250);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85,85,255);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(148, 146, 149);\n"
"}")
        self.returnbutton.setIcon(icon)
        self.returnbutton.setObjectName("returnbutton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 110, 63, 14))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 63, 14))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 220, 63, 14))
        self.label_3.setObjectName("label_3")
        self.two = QtWidgets.QLineEdit(Form)
        self.two.setGeometry(QtCore.QRect(150, 140, 111, 45))
        self.two.setMinimumSize(QtCore.QSize(0, 45))
        self.two.setMaximumSize(QtCore.QSize(16777215, 45))
        self.two.setStyleSheet("QLineEdit {\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;\n"
"    background-color: transparent;\n"
"}\n"
"QLineEdit: hover{\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"QLineEdit: focus \n"
"{\n"
"     border-bottom: 1px solid rgb(18,183,245);\n"
"}")
        self.two.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.two.setObjectName("two")
        self.one = QtWidgets.QLineEdit(Form)
        self.one.setGeometry(QtCore.QRect(150, 90, 111, 45))
        self.one.setMinimumSize(QtCore.QSize(0, 45))
        self.one.setMaximumSize(QtCore.QSize(16777215, 45))
        self.one.setStyleSheet("QLineEdit {\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;\n"
"    background-color: transparent;\n"
"}\n"
"QLineEdit: hover{\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"QLineEdit: focus \n"
"{\n"
"     border-bottom: 1px solid rgb(18,183,245);\n"
"}")
        self.one.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.one.setObjectName("one")
        self.condition = QtWidgets.QPushButton(Form)
        self.condition.setEnabled(True)
        self.condition.setGeometry(QtCore.QRect(390, 330, 231, 45))
        self.condition.setMinimumSize(QtCore.QSize(0, 45))
        self.condition.setMaximumSize(QtCore.QSize(16777215, 45))
        self.condition.setStyleSheet("QPushButton {\n"
"    background-color: rgb(33,174,250);\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(72,203,250);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85,85,255);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(148, 146, 149);\n"
"}")
        self.condition.setIcon(icon)
        self.condition.setObjectName("condition")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(270, 30, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9.33333pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">恭喜您进入游戏！</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">请选择单项选择题、判断题和简答题的数量！</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">最多每项20个</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("Form", "Python答题游戏"))
        self.submit.setText(_translate("Form", "提交"))
        self.returnbutton.setText(_translate("Form", "返回登录界面"))
        self.label.setText(_translate("Form", "单选题"))
        self.label_2.setText(_translate("Form", "判断题"))
        self.label_3.setText(_translate("Form", "简答题"))
        self.condition.setText(_translate("Form", "查看本人做题情况"))
