# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(672, 453)
        Form.setAcceptDrops(False)
        Form.setAutoFillBackground(False)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 50, 581, 401))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.login_bottom_2 = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.login_bottom_2.setEnabled(True)
        self.login_bottom_2.setToolTipDuration(-15)
        self.login_bottom_2.setStyleSheet("")
        self.login_bottom_2.setObjectName("login_bottom_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.login_bottom_2)
        self.horizontalLayout_4.setContentsMargins(20, 0, 20, 20)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.login_bottom_2)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignBottom)
        self.widget_4 = QtWidgets.QWidget(self.login_bottom_2)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pwd = QtWidgets.QLineEdit(self.widget_4)
        self.pwd.setMinimumSize(QtCore.QSize(0, 45))
        self.pwd.setMaximumSize(QtCore.QSize(16777215, 45))
        self.pwd.setStyleSheet("QLineEdit {\n"
                               "    font-size: 20px;\n"
                               "    border: none;\n"
                               "    border-bottom: 1px solid gray;\n"
                               "    background-color: transparent;\n"
                               "}\n"
                               "QLineEdit: hover{\n"
                               "    border-bottom: 1px solid black;\n"
                               "}\n"
                               "QLineEdit: focus \n"
                               "{\n"
                               "     border-bottom: 1px solid rgb(18,183,245);\n"
                               "}")
        self.pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd.setObjectName("pwd")
        self.gridLayout_2.addWidget(self.pwd, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.login_btn = QtWidgets.QPushButton(self.widget_4)
        self.login_btn.setEnabled(True)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 45))
        self.login_btn.setMaximumSize(QtCore.QSize(16777215, 45))
        self.login_btn.setStyleSheet("QPushButton {\n"
                                     "    background-color: rgb(33,174,250);\n"
                                     "    border-radius: 5px;\n"
                                     "    color: white;\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "    background-color: rgb(72,203,250);\n"
                                     "}\n"
                                     "QPushButton:pressed {\n"
                                     "    background-color: rgb(85,85,255);\n"
                                     "}\n"
                                     "QPushButton:disabled {\n"
                                     "    background-color: rgb(148, 146, 149);\n"
                                     "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/login/images/safe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_btn.setIcon(icon)
        self.login_btn.setObjectName("login_btn")
        self.gridLayout_2.addWidget(self.login_btn, 6, 0, 1, 2)
        self.name = QtWidgets.QLineEdit(self.widget_4)
        self.name.setMinimumSize(QtCore.QSize(0, 45))
        self.name.setMaximumSize(QtCore.QSize(16777215, 45))
        self.name.setStyleSheet("QLineEdit {\n"
                                "    font-size: 20px;\n"
                                "    border: none;\n"
                                "    border-bottom: 1px solid gray;\n"
                                "    background-color: transparent;\n"
                                "}\n"
                                "QLineEdit: hover{\n"
                                "    border-bottom: 1px solid black;\n"
                                "}\n"
                                "QLineEdit: focus \n"
                                "{\n"
                                "     border-bottom: 1px solid rgb(18,183,245);\n"
                                "}")
        self.name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 0, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.label_3 = QtWidgets.QLabel(self.login_bottom_2)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 6)
        self.horizontalLayout_3.addWidget(self.login_bottom_2)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "注册账号"))
        self.label_2.setText(_translate("Form", "密码"))
        self.label.setText(_translate("Form", "账号"))
        self.login_btn.setText(_translate("Form", "登录"))
        self.label_4.setText(_translate("Form", "Python答题游戏"))
