# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'situation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(673, 559)
        self.returnbutton = QtWidgets.QPushButton(Form)
        self.returnbutton.setEnabled(True)
        self.returnbutton.setGeometry(QtCore.QRect(560, 20, 91, 45))
        self.returnbutton.setMinimumSize(QtCore.QSize(0, 45))
        self.returnbutton.setMaximumSize(QtCore.QSize(16777215, 45))
        self.returnbutton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(33,174,250);\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(72,203,250);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85,85,255);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(148, 146, 149);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/login/images/safe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.returnbutton.setIcon(icon)
        self.returnbutton.setObjectName("returnbutton")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 361, 241))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 270, 361, 241))
        self.groupBox_2.setObjectName("groupBox_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.returnbutton.setText(_translate("Form", "返回主界面"))
        self.groupBox.setTitle(_translate("Form", "条形图"))
        self.groupBox_2.setTitle(_translate("Form", "折线图"))
